### PR TITLE
merge peerDependencies when comparing npm packages

### PR DESCRIPTION
**Pull request by FabianMeul**

### CODE REVIEW

**Comment by Silic0nS0ldier** [comment]
Looks good. Yarn is designed to be fully compliant with NPM so add the peer dependency string to that as well, and I'll merge.

When I have the chance I'll push a new release out.

**Comment by FabianMeul** [comment]
Any chance of putting out a new release for this @Silic0nS0ldier ? :-)

**Comment by Silic0nS0ldier** [comment]
Completely forgot about this sorry. As I recall, I'd gone to make a new release and screwed it up before publish (my bad for thinking publishing late at night was a good idea). This then was forgotten entirely (been a busy month).

I don't want to repeat the screw up (focus is 100% on an exam at the moment), so I'll set a reminder for tomorrow.

**Comment by Silic0nS0ldier** [comment]
Alright, I've published v1.2.0 which includes this.

**Pull request merged**
